name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository Code
        uses: actions/checkout@v3
      - name: set up JDK 8
        uses: actions/setup-java@v3
        with:
         java-version: '8'
         distribution: 'temurin'
      - name: Test Result
        run: |
          cd src
          javac -d . *.java
          java Main ./test/code
