name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository Code
        uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v3
      - name: Build project
        run: javac -d . *.java
      - name: Test project
        run: java Main.java ./test/code
